### ISSUE TITLE
Could not find package carbontwelve/tapestry

### ISSUE THREAD

**Issue by wdmtech** [carbontwelve/tapestry#11]
Because I tried to take the lazy option to start a project - I tried globally requiring tapestry, but then saw it's not on packagist yet... d'oh!

https://packagist.org/search/?q=carbontwelve

**Comment by carbontwelve** [comment]
https://packagist.org/packages/carbontwelve/tapestry :)

This is fixed by 36db99ec3e9d00ccc4fa3db8ba64789f0372496c
